#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from kim.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "kim.y"

#define YYSTYPE_IS_DECLARED 1
typedef long YYSTYPE;
#include"type.h"
extern int line_no,syntax_err;
extern A_NODE *root;
extern A_ID *current_id;
extern int current_level;
extern A_TYPE *int_type;
void yyerror(char *s);
A_NODE *makeNode(NODE_NAME, A_NODE *, A_NODE *, A_NODE *);
A_NODE *makeNodeList(NODE_NAME, A_NODE *, A_NODE *);
A_ID *makeIdentifier(char *);
A_ID *makeDummyIdentifier();
A_TYPE *makeType(T_KIND);
A_SPECIFIER *makeSpecifier(A_TYPE *, S_KIND);
A_ID *searchIdentifier(char *, A_ID *);
A_ID *searchIdentifierAtCurrentLevel(char *, A_ID *);
A_SPECIFIER *updateSpecifier(A_SPECIFIER *, A_TYPE *, S_KIND);
void checkForwardReference();
void setDefaultSpecifier(A_SPECIFIER *);
A_ID *linkDeclaratorList(A_ID *, A_ID *);
A_ID *getIdentifierDeclared(char *);
A_TYPE *getTypeOfStructOrEnumRefIdentifier(T_KIND , char *, ID_KIND);
A_ID  *setDeclaratorInit(A_ID *,  A_NODE *);
A_ID  *setDeclaratorKind(A_ID *,  ID_KIND);
A_ID  *setDeclaratorType(A_ID *,  A_TYPE *);
A_ID  *setDeclaratorElementType(A_ID *, A_TYPE *);
A_ID  *setDeclaratorTypeAndKind(A_ID *, A_TYPE *, ID_KIND);
A_ID  *setDeclaratorListSpecifier(A_ID *, A_SPECIFIER *);
A_ID  *setFunctionDeclaratorSpecifier(A_ID *, A_SPECIFIER *);
A_ID  *setFunctionDeclaratorBody(A_ID *, A_NODE *);
A_ID  *setParameterDeclaratorSpecifier(A_ID *, A_SPECIFIER *);
A_ID  *setStructDeclaratorListSpecifier(A_ID *, A_TYPE *);
A_TYPE *setTypeNameSpecifier(A_TYPE *, A_SPECIFIER *);
A_TYPE *setTypeElementType(A_TYPE *, A_TYPE *);
A_TYPE *setTypeField(A_TYPE *, A_ID *);
A_TYPE *setTypeExpr(A_TYPE *, A_NODE *);
A_TYPE *setTypeAndKindOfDeclarator(A_TYPE *, ID_KIND, A_ID *);
A_TYPE *setTypeStructOrEnumIdentifier(T_KIND, char *, ID_KIND);
BOOLEAN isNotSameFormalParameters(A_ID *, A_ID *);
BOOLEAN isNotSameType(A_TYPE *, A_TYPE *);
BOOLEAN isPointOrArrayType(A_TYPE *);
int yywrap(void)
{
		return 1;
}

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE long
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENTIFIER	258
#define	TYPE_IDENTIFIER	259
#define	FLOAT_CONSTANT	260
#define	INTEGER_CONSTANT	261
#define	CHARACTER_CONSTANT	262
#define	STRING_LITERAL	263
#define	PLUS	264
#define	MINUS	265
#define	PLUSPLUS	266
#define	MINUSMINUS	267
#define	BAR	268
#define	AMP	269
#define	BARBAR	270
#define	AMPAMP	271
#define	ARROW	272
#define	SEMICOLON	273
#define	LSS	274
#define	GTR	275
#define	LEQ	276
#define	GEQ	277
#define	EQL	278
#define	NEQ	279
#define	DOTDOTDOT	280
#define	LP	281
#define	RP	282
#define	LB	283
#define	RB	284
#define	LR	285
#define	RR	286
#define	PERIOD	287
#define	COMMA	288
#define	EXCL	289
#define	STAR	290
#define	SLASH	291
#define	PERCENT	292
#define	ASSIGN	293
#define	COLON	294
#define	AUTO_SYM	295
#define	STATIC_SYM	296
#define	TYPEDEF_SYM	297
#define	STRUCT_SYM	298
#define	ENUM_SYM	299
#define	SIZEOF_SYM	300
#define	UNION_SYM	301
#define	IF_SYM	302
#define	ELSE_SYM	303
#define	WHILE_SYM	304
#define	DO_SYM	305
#define	FOR_SYM	306
#define	CONTINUE_SYM	307
#define	BREAK_SYM	308
#define	RETURN_SYM	309
#define	SWITCH_SYM	310
#define	CASE_SYM	311
#define	DEFAULT_SYM	312


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENTIFIER;
static const int TYPE_IDENTIFIER;
static const int FLOAT_CONSTANT;
static const int INTEGER_CONSTANT;
static const int CHARACTER_CONSTANT;
static const int STRING_LITERAL;
static const int PLUS;
static const int MINUS;
static const int PLUSPLUS;
static const int MINUSMINUS;
static const int BAR;
static const int AMP;
static const int BARBAR;
static const int AMPAMP;
static const int ARROW;
static const int SEMICOLON;
static const int LSS;
static const int GTR;
static const int LEQ;
static const int GEQ;
static const int EQL;
static const int NEQ;
static const int DOTDOTDOT;
static const int LP;
static const int RP;
static const int LB;
static const int RB;
static const int LR;
static const int RR;
static const int PERIOD;
static const int COMMA;
static const int EXCL;
static const int STAR;
static const int SLASH;
static const int PERCENT;
static const int ASSIGN;
static const int COLON;
static const int AUTO_SYM;
static const int STATIC_SYM;
static const int TYPEDEF_SYM;
static const int STRUCT_SYM;
static const int ENUM_SYM;
static const int SIZEOF_SYM;
static const int UNION_SYM;
static const int IF_SYM;
static const int ELSE_SYM;
static const int WHILE_SYM;
static const int DO_SYM;
static const int FOR_SYM;
static const int CONTINUE_SYM;
static const int BREAK_SYM;
static const int RETURN_SYM;
static const int SWITCH_SYM;
static const int CASE_SYM;
static const int DEFAULT_SYM;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENTIFIER=258
	,TYPE_IDENTIFIER=259
	,FLOAT_CONSTANT=260
	,INTEGER_CONSTANT=261
	,CHARACTER_CONSTANT=262
	,STRING_LITERAL=263
	,PLUS=264
	,MINUS=265
	,PLUSPLUS=266
	,MINUSMINUS=267
	,BAR=268
	,AMP=269
	,BARBAR=270
	,AMPAMP=271
	,ARROW=272
	,SEMICOLON=273
	,LSS=274
	,GTR=275
	,LEQ=276
	,GEQ=277
	,EQL=278
	,NEQ=279
	,DOTDOTDOT=280
	,LP=281
	,RP=282
	,LB=283
	,RB=284
	,LR=285
	,RR=286
	,PERIOD=287
	,COMMA=288
	,EXCL=289
	,STAR=290
	,SLASH=291
	,PERCENT=292
	,ASSIGN=293
	,COLON=294
	,AUTO_SYM=295
	,STATIC_SYM=296
	,TYPEDEF_SYM=297
	,STRUCT_SYM=298
	,ENUM_SYM=299
	,SIZEOF_SYM=300
	,UNION_SYM=301
	,IF_SYM=302
	,ELSE_SYM=303
	,WHILE_SYM=304
	,DO_SYM=305
	,FOR_SYM=306
	,CONTINUE_SYM=307
	,BREAK_SYM=308
	,RETURN_SYM=309
	,SWITCH_SYM=310
	,CASE_SYM=311
	,DEFAULT_SYM=312


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENTIFIER=258;
const int YY_parse_CLASS::TYPE_IDENTIFIER=259;
const int YY_parse_CLASS::FLOAT_CONSTANT=260;
const int YY_parse_CLASS::INTEGER_CONSTANT=261;
const int YY_parse_CLASS::CHARACTER_CONSTANT=262;
const int YY_parse_CLASS::STRING_LITERAL=263;
const int YY_parse_CLASS::PLUS=264;
const int YY_parse_CLASS::MINUS=265;
const int YY_parse_CLASS::PLUSPLUS=266;
const int YY_parse_CLASS::MINUSMINUS=267;
const int YY_parse_CLASS::BAR=268;
const int YY_parse_CLASS::AMP=269;
const int YY_parse_CLASS::BARBAR=270;
const int YY_parse_CLASS::AMPAMP=271;
const int YY_parse_CLASS::ARROW=272;
const int YY_parse_CLASS::SEMICOLON=273;
const int YY_parse_CLASS::LSS=274;
const int YY_parse_CLASS::GTR=275;
const int YY_parse_CLASS::LEQ=276;
const int YY_parse_CLASS::GEQ=277;
const int YY_parse_CLASS::EQL=278;
const int YY_parse_CLASS::NEQ=279;
const int YY_parse_CLASS::DOTDOTDOT=280;
const int YY_parse_CLASS::LP=281;
const int YY_parse_CLASS::RP=282;
const int YY_parse_CLASS::LB=283;
const int YY_parse_CLASS::RB=284;
const int YY_parse_CLASS::LR=285;
const int YY_parse_CLASS::RR=286;
const int YY_parse_CLASS::PERIOD=287;
const int YY_parse_CLASS::COMMA=288;
const int YY_parse_CLASS::EXCL=289;
const int YY_parse_CLASS::STAR=290;
const int YY_parse_CLASS::SLASH=291;
const int YY_parse_CLASS::PERCENT=292;
const int YY_parse_CLASS::ASSIGN=293;
const int YY_parse_CLASS::COLON=294;
const int YY_parse_CLASS::AUTO_SYM=295;
const int YY_parse_CLASS::STATIC_SYM=296;
const int YY_parse_CLASS::TYPEDEF_SYM=297;
const int YY_parse_CLASS::STRUCT_SYM=298;
const int YY_parse_CLASS::ENUM_SYM=299;
const int YY_parse_CLASS::SIZEOF_SYM=300;
const int YY_parse_CLASS::UNION_SYM=301;
const int YY_parse_CLASS::IF_SYM=302;
const int YY_parse_CLASS::ELSE_SYM=303;
const int YY_parse_CLASS::WHILE_SYM=304;
const int YY_parse_CLASS::DO_SYM=305;
const int YY_parse_CLASS::FOR_SYM=306;
const int YY_parse_CLASS::CONTINUE_SYM=307;
const int YY_parse_CLASS::BREAK_SYM=308;
const int YY_parse_CLASS::RETURN_SYM=309;
const int YY_parse_CLASS::SWITCH_SYM=310;
const int YY_parse_CLASS::CASE_SYM=311;
const int YY_parse_CLASS::DEFAULT_SYM=312;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		293
#define	YYFLAG		-32768
#define	YYNTBASE	58

#define YYTRANSLATE(x) ((unsigned)(x) <= 312 ? yytranslate[x] : 137)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     7,     9,    11,    12,    17,    18,    22,
    23,    25,    27,    30,    34,    36,    38,    41,    44,    46,
    48,    50,    51,    53,    55,    59,    61,    65,    67,    71,
    73,    77,    79,    81,    83,    84,    85,    93,    94,    95,
   102,   105,   107,   109,   111,   114,   118,   120,   124,   126,
   127,   134,   135,   141,   144,   146,   150,   152,   153,   158,
   161,   163,   165,   168,   170,   174,   179,   180,   186,   187,
   189,   191,   195,   197,   201,   204,   207,   208,   210,   212,
   214,   217,   221,   225,   230,   234,   239,   240,   242,   244,
   247,   249,   251,   253,   255,   257,   259,   264,   268,   269,
   275,   277,   280,   286,   294,   300,   306,   314,   320,   326,
   327,   329,   333,   336,   339,   340,   342,   344,   348,   349,
   351,   353,   355,   357,   359,   363,   365,   367,   371,   373,
   377,   379,   381,   383,   385,   389,   393,   395,   399,   403,
   407,   411,   413,   415,   419,   423,   425,   429,   433,   437,
   439,   444,   446,   449,   452,   455,   458,   461,   464,   467,
   470,   475,   477,   482,   487,   491,   495,   498,   501,   503,
   505,   507,   509,   511,   515
};

static const short yyrhs[] = {    59,
     0,    60,     0,    59,    60,     0,    61,     0,    66,     0,
     0,    67,    91,    62,   106,     0,     0,    91,    63,   106,
     0,     0,    65,     0,    66,     0,    65,    66,     0,    67,
    69,    18,     0,    74,     0,    68,     0,    74,    67,     0,
    68,    67,     0,    40,     0,    41,     0,    42,     0,     0,
    70,     0,    71,     0,    70,    33,    71,     0,    91,     0,
    91,    38,    72,     0,   117,     0,    30,    73,    31,     0,
    72,     0,    73,    33,    72,     0,    75,     0,    85,     0,
     4,     0,     0,     0,    80,     3,    76,    30,    77,    81,
    31,     0,     0,     0,    80,    78,    30,    79,    81,    31,
     0,    80,     3,     0,    43,     0,    46,     0,    82,     0,
    81,    82,     0,    74,    83,    18,     0,    84,     0,    83,
    33,    84,     0,    91,     0,     0,    44,     3,    86,    30,
    88,    31,     0,     0,    44,    87,    30,    88,    31,     0,
    44,     3,     0,    89,     0,    88,    33,    89,     0,     3,
     0,     0,     3,    90,    38,   118,     0,    92,    93,     0,
    93,     0,    35,     0,    35,    92,     0,     3,     0,    26,
    91,    27,     0,    93,    28,   116,    29,     0,     0,    93,
    26,    94,    95,    27,     0,     0,    96,     0,    97,     0,
    97,    33,    25,     0,    98,     0,    97,    33,    98,     0,
    67,    91,     0,    67,    99,     0,     0,   100,     0,   101,
     0,    92,     0,    92,   101,     0,    26,   100,    27,     0,
    28,   116,    29,     0,   101,    28,   116,    29,     0,    26,
    95,    27,     0,   101,    26,    95,    27,     0,     0,   103,
     0,   104,     0,   103,   104,     0,   105,     0,   106,     0,
   108,     0,   109,     0,   110,     0,   113,     0,    56,   117,
    39,   104,     0,    57,    39,   104,     0,     0,    30,   107,
    64,   102,    31,     0,    18,     0,   118,    18,     0,    47,
    26,   118,    27,   104,     0,    47,    26,   118,    27,   104,
    48,   104,     0,    55,    26,   118,    27,   104,     0,    49,
    26,   118,    27,   104,     0,    50,   104,    49,    26,   118,
    27,    18,     0,    51,    26,   111,    27,   104,     0,   112,
    18,   112,    18,   112,     0,     0,   118,     0,    54,   112,
    18,     0,    52,    18,     0,    53,    18,     0,     0,   115,
     0,   120,     0,   115,    33,   120,     0,     0,   117,     0,
   118,     0,   119,     0,   120,     0,   121,     0,   133,    38,
   120,     0,   122,     0,   123,     0,   122,    15,   123,     0,
   124,     0,   123,    16,   124,     0,   125,     0,   126,     0,
   127,     0,   128,     0,   127,    23,   128,     0,   127,    24,
   128,     0,   129,     0,   128,    19,   129,     0,   128,    20,
   129,     0,   128,    21,   129,     0,   128,    22,   129,     0,
   130,     0,   131,     0,   130,     9,   131,     0,   130,    10,
   131,     0,   132,     0,   131,    35,   132,     0,   131,    36,
   132,     0,   131,    37,   132,     0,   133,     0,    26,   136,
    27,   132,     0,   134,     0,    11,   133,     0,    12,   133,
     0,    14,   132,     0,    35,   132,     0,    34,   132,     0,
    10,   132,     0,     9,   132,     0,    45,   133,     0,    45,
    26,   136,    27,     0,   135,     0,   134,    28,   118,    29,
     0,   134,    26,   114,    27,     0,   134,    32,     3,     0,
   134,    17,     3,     0,   134,    11,     0,   134,    12,     0,
     3,     0,     6,     0,     5,     0,     7,     0,     8,     0,
    26,   118,    27,     0,    67,    99,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    60,    63,    64,    67,    68,    71,    72,    73,    74,    77,
    78,    81,    82,    85,    89,    90,    91,    92,    95,    96,
    97,   100,   101,   104,   105,   108,   109,   112,   113,   116,
   117,   120,   121,   122,   125,   126,   126,   128,   128,   129,
   131,   134,   135,   138,   139,   142,   146,   147,   151,   154,
   155,   156,   157,   158,   161,   162,   165,   166,   167,   170,
   171,   174,   175,   178,   179,   180,   181,   182,   186,   187,
   190,   191,   194,   195,   198,   199,   203,   204,   207,   208,
   209,   212,   213,   214,   216,   217,   221,   222,   225,   226,
   229,   230,   231,   232,   233,   234,   237,   238,   241,   242,
   246,   247,   250,   251,   253,   256,   257,   259,   262,   266,
   267,   270,   271,   272,   275,   276,   279,   280,   284,   285,
   288,   291,   294,   297,   298,   302,   305,   306,   310,   311,
   315,   318,   321,   324,   325,   326,   329,   330,   331,   332,
   333,   336,   339,   340,   341,   344,   345,   346,   347,   350,
   351,   354,   355,   356,   357,   358,   359,   360,   361,   362,
   363,   366,   367,   368,   369,   370,   371,   372,   375,   376,
   377,   378,   379,   380,   383
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENTIFIER",
"TYPE_IDENTIFIER","FLOAT_CONSTANT","INTEGER_CONSTANT","CHARACTER_CONSTANT","STRING_LITERAL",
"PLUS","MINUS","PLUSPLUS","MINUSMINUS","BAR","AMP","BARBAR","AMPAMP","ARROW",
"SEMICOLON","LSS","GTR","LEQ","GEQ","EQL","NEQ","DOTDOTDOT","LP","RP","LB","RB",
"LR","RR","PERIOD","COMMA","EXCL","STAR","SLASH","PERCENT","ASSIGN","COLON",
"AUTO_SYM","STATIC_SYM","TYPEDEF_SYM","STRUCT_SYM","ENUM_SYM","SIZEOF_SYM","UNION_SYM",
"IF_SYM","ELSE_SYM","WHILE_SYM","DO_SYM","FOR_SYM","CONTINUE_SYM","BREAK_SYM",
"RETURN_SYM","SWITCH_SYM","CASE_SYM","DEFAULT_SYM","program","translation_unit",
"external_declaration","function_definition","@1","@2","declaration_list_opt",
"declaration_list","declaration","declaration_specifiers","storage_class_specifier",
"init_declarator_list_opt","init_declarator_list","init_declarator","initializer",
"initializer_list","type_specifier","struct_type_specifier","@3","@4","@5","@6",
"struct_or_union","struct_declaration_list","struct_declaration","struct_declarator_list",
"struct_declarator","enum_type_specifier","@7","@8","enumerator_list","enumerator",
"@9","declarator","pointer","direct_declarator","@10","parameter_type_list_opt",
"parameter_type_list","parameter_list","parameter_declaration","abstract_declarator_opt",
"abstract_declarator","direct_abstract_declarator","statement_list_opt","statement_list",
"statement","labeled_statement","compound_statement","@11","expression_statement",
"selection_statement","iteration_statement","for_expression","expression_opt",
"jump_statement","arg_expression_list_opt","arg_expression_list","constant_expression_opt",
"constant_expression","expression","comma_expression","assignment_expression",
"conditional_expression","logical_or_expression","logical_and_expression","bitwise_or_expression",
"bitwise_xor_expression","bitwise_and_expression","equality_expression","relational_expression",
"shift_expression","additive_expression","multiplicative_expression","cast_expression",
"unary_expression","postfix_expression","primary_expression","type_name",""
};
#endif

static const short yyr1[] = {     0,
    58,    59,    59,    60,    60,    62,    61,    63,    61,    64,
    64,    65,    65,    66,    67,    67,    67,    67,    68,    68,
    68,    69,    69,    70,    70,    71,    71,    72,    72,    73,
    73,    74,    74,    74,    76,    77,    75,    78,    79,    75,
    75,    80,    80,    81,    81,    82,    83,    83,    84,    86,
    85,    87,    85,    85,    88,    88,    89,    90,    89,    91,
    91,    92,    92,    93,    93,    93,    94,    93,    95,    95,
    96,    96,    97,    97,    98,    98,    99,    99,   100,   100,
   100,   101,   101,   101,   101,   101,   102,   102,   103,   103,
   104,   104,   104,   104,   104,   104,   105,   105,   107,   106,
   108,   108,   109,   109,   109,   110,   110,   110,   111,   112,
   112,   113,   113,   113,   114,   114,   115,   115,   116,   116,
   117,   118,   119,   120,   120,   121,   122,   122,   123,   123,
   124,   125,   126,   127,   127,   127,   128,   128,   128,   128,
   128,   129,   130,   130,   130,   131,   131,   131,   131,   132,
   132,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   134,   134,   134,   134,   134,   134,   134,   135,   135,
   135,   135,   135,   135,   136
};

static const short yyr2[] = {     0,
     1,     1,     2,     1,     1,     0,     4,     0,     3,     0,
     1,     1,     2,     3,     1,     1,     2,     2,     1,     1,
     1,     0,     1,     1,     3,     1,     3,     1,     3,     1,
     3,     1,     1,     1,     0,     0,     7,     0,     0,     6,
     2,     1,     1,     1,     2,     3,     1,     3,     1,     0,
     6,     0,     5,     2,     1,     3,     1,     0,     4,     2,
     1,     1,     2,     1,     3,     4,     0,     5,     0,     1,
     1,     3,     1,     3,     2,     2,     0,     1,     1,     1,
     2,     3,     3,     4,     3,     4,     0,     1,     1,     2,
     1,     1,     1,     1,     1,     1,     4,     3,     0,     5,
     1,     2,     5,     7,     5,     5,     7,     5,     5,     0,
     1,     3,     2,     2,     0,     1,     1,     3,     0,     1,
     1,     1,     1,     1,     3,     1,     1,     3,     1,     3,
     1,     1,     1,     1,     3,     3,     1,     3,     3,     3,
     3,     1,     1,     3,     3,     1,     3,     3,     3,     1,
     4,     1,     2,     2,     2,     2,     2,     2,     2,     2,
     4,     1,     4,     4,     3,     3,     2,     2,     1,     1,
     1,     1,     1,     3,     2
};

static const short yydefact[] = {     0,
    64,    34,     0,    62,    19,    20,    21,    42,    52,    43,
     1,     2,     4,     5,    22,    16,    15,    32,    38,    33,
     8,     0,    61,     0,    63,    54,     0,     3,     0,    23,
    24,    26,    18,    17,    41,     0,     0,    60,    67,   119,
    65,     0,     0,    14,     0,     0,     0,     0,    39,    99,
     9,    69,   169,   171,   170,   172,   173,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   120,   121,   122,
   123,   124,   126,   127,   129,   131,   132,   133,   134,   137,
   142,   143,   146,   150,   152,   162,     0,    57,     0,    55,
    25,    26,     0,    27,    28,     7,    36,     0,    10,    77,
     0,    70,    71,    73,   159,   150,   158,     0,   153,   154,
   155,    77,     0,     0,   157,   156,     0,   160,    66,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   167,   168,     0,   115,     0,     0,     0,
     0,    53,     0,    30,     0,     0,     0,     0,    44,    87,
    11,    12,    22,    69,   119,    75,    80,    76,    78,    79,
    68,     0,    69,    80,   175,   174,     0,     0,   128,   130,
   135,   136,   138,   139,   140,   141,   144,   145,   147,   148,
   149,   125,   166,     0,   116,   117,     0,   165,    51,     0,
    56,    29,     0,     0,     0,    47,    49,    40,    45,   101,
     0,     0,     0,     0,     0,     0,   110,     0,     0,     0,
     0,    88,    89,    91,    92,    93,    94,    95,    96,     0,
    13,     0,     0,     0,    81,    69,   119,    72,    74,   151,
   161,   164,     0,   163,    59,    31,    37,    46,     0,     0,
     0,     0,   110,   113,   114,     0,   111,     0,     0,     0,
   100,    90,   102,    85,    82,    83,     0,     0,   118,    48,
     0,     0,     0,     0,     0,   112,     0,     0,    98,    86,
    84,     0,     0,     0,     0,   110,     0,    97,   103,   106,
     0,   108,     0,   105,     0,     0,   110,   104,   107,   109,
     0,     0,     0
};

static const short yydefgoto[] = {   291,
    11,    12,    13,    47,    37,   150,   151,    14,   100,    16,
    29,    30,    31,    94,   145,    17,    18,    48,   146,    36,
    98,    19,   148,   149,   195,   196,    20,    42,    27,    89,
    90,   141,    21,    22,    23,    52,   222,   102,   103,   104,
   158,   159,   160,   211,   212,   213,   214,   215,    99,   216,
   217,   218,   264,   246,   219,   184,   185,    67,    68,   220,
    70,    71,    72,    73,    74,    75,    76,    77,    78,    79,
    80,    81,    82,    83,    84,    85,    86,   114
};

static const short yypact[] = {   180,
-32768,-32768,    34,    27,-32768,-32768,-32768,-32768,    68,-32768,
   180,-32768,-32768,-32768,    34,    70,    70,-32768,    77,-32768,
-32768,    17,    22,    72,-32768,    76,    88,-32768,   104,   103,
-32768,    62,-32768,-32768,   107,   111,   112,    22,-32768,   372,
-32768,   122,   148,-32768,    34,   359,   112,   133,-32768,-32768,
-32768,    70,-32768,-32768,-32768,-32768,-32768,   372,   372,   413,
   413,   372,   315,   372,   372,   426,   131,-32768,-32768,-32768,
-32768,-32768,   151,   157,-32768,-32768,-32768,    12,   125,-32768,
    66,   121,-32768,   143,   199,-32768,   148,   147,    92,-32768,
-32768,   155,   359,-32768,-32768,-32768,-32768,    21,    70,    19,
   159,-32768,   141,-32768,-32768,-32768,-32768,   372,-32768,-32768,
-32768,     6,   178,   182,-32768,-32768,   315,-32768,-32768,   372,
   372,   372,   372,   372,   372,   372,   372,   372,   372,   372,
   372,   372,   372,-32768,-32768,   195,   372,   372,   204,   101,
   174,-32768,   148,-32768,   139,    21,    34,    35,-32768,   260,
    70,-32768,    34,   136,   372,-32768,    93,-32768,-32768,   171,
-32768,    47,   302,   176,-32768,-32768,   372,   186,   157,-32768,
   125,   125,-32768,-32768,-32768,-32768,   121,   121,-32768,-32768,
-32768,-32768,-32768,   187,   184,-32768,   189,-32768,-32768,   372,
-32768,-32768,   359,    51,    11,-32768,-32768,-32768,-32768,-32768,
   193,   202,   260,   203,   212,   214,   372,   207,   372,   196,
   206,   260,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   220,
-32768,   218,   219,   210,   171,    70,   372,-32768,-32768,-32768,
-32768,-32768,   372,-32768,-32768,-32768,-32768,-32768,    34,   372,
   372,   200,   372,-32768,-32768,   230,-32768,   372,   225,   260,
-32768,-32768,-32768,-32768,-32768,-32768,   246,   247,-32768,-32768,
   248,   250,   253,   254,   262,-32768,   255,   260,-32768,-32768,
-32768,   260,   260,   372,   260,   372,   260,-32768,   235,-32768,
   257,-32768,   267,-32768,   260,   269,   372,-32768,-32768,-32768,
   288,   289,-32768
};

static const short yypgoto[] = {-32768,
-32768,   280,-32768,-32768,-32768,-32768,-32768,   -94,    10,-32768,
-32768,-32768,   251,   -86,-32768,   -90,-32768,-32768,-32768,-32768,
-32768,-32768,   146,  -135,-32768,    54,-32768,-32768,-32768,   211,
   156,-32768,     1,     5,   -19,-32768,   -51,-32768,-32768,   138,
   190,  -121,  -126,-32768,-32768,  -142,-32768,    -7,-32768,-32768,
-32768,-32768,-32768,  -224,-32768,-32768,-32768,  -141,   -44,   -40,
-32768,  -109,-32768,-32768,   181,   183,-32768,-32768,-32768,   -20,
   117,-32768,     0,   -47,   130,-32768,-32768,   191
};


#define	YYLAST		471


static const short yytable[] = {    69,
   101,    95,    38,    24,   152,    69,   144,   147,    25,    15,
   105,   107,   199,   224,   111,    32,   115,   116,   265,     1,
    15,     1,   113,   182,     2,    33,    34,   186,   238,    51,
   225,   163,   223,   155,   122,   123,     1,   225,     2,    96,
     4,   223,     3,   239,   154,    92,   155,    39,    95,    40,
     2,   283,    69,     4,     2,   147,   221,   147,   199,     3,
   242,     4,   290,     8,     9,   198,    10,   113,     4,   252,
    26,   228,   112,     2,   128,   129,   113,     8,     9,    35,
    10,   237,   179,   180,   181,   258,     5,     6,     7,     8,
     9,    -6,    10,     8,     9,     1,    10,   187,    41,    46,
   156,   171,   172,   147,   157,   -50,   236,   269,   153,     5,
     6,     7,     8,     9,    69,    10,   164,    43,   154,   230,
   155,    44,   142,   259,   143,   278,   112,   177,   178,   279,
   280,   189,   282,   143,   284,    45,   -35,    38,     1,     2,
    49,    50,   288,   124,   125,   126,   127,   197,    95,   235,
    88,    87,    69,    92,    24,   130,   131,   132,   157,   119,
   153,   154,    97,   155,   249,   120,   247,   164,    69,   192,
     4,   193,   121,   162,   257,     5,     6,     7,     8,     9,
   133,    10,     1,     2,   -58,   161,    69,   106,   106,   109,
   110,   106,    46,   106,   106,   118,   226,   183,   227,   261,
   262,   163,   247,   155,   166,     3,   188,   267,   167,   134,
   135,   190,   231,   232,     4,   136,   233,   234,   240,     5,
     6,     7,     8,     9,   137,    10,   138,   241,   243,   244,
   139,   245,   248,   281,   250,   247,   251,   253,   256,   197,
   173,   174,   175,   176,   254,   255,   247,   266,   263,   106,
   106,   106,   106,   106,   106,   106,   106,   106,   106,   106,
   106,   106,    53,   268,    54,    55,    56,    57,    58,    59,
    60,    61,   270,    62,   272,   271,   273,   200,   274,   276,
   275,   277,   285,   286,   287,    63,   289,   292,   293,    50,
    28,   194,   260,    64,    65,    91,   106,   140,   191,   229,
   169,   165,     0,   170,    66,     2,   201,   168,   202,   203,
   204,   205,   206,   207,   208,   209,   210,    53,     2,    54,
    55,    56,    57,    58,    59,    60,    61,   163,    62,   155,
     0,     0,     0,     0,     0,     0,     4,     0,     0,     0,
    63,     5,     6,     7,     8,     9,     0,    10,    64,    65,
     0,     0,     0,     0,     5,     6,     7,     8,     9,    66,
    10,    53,     0,    54,    55,    56,    57,    58,    59,    60,
    61,     0,    62,     0,    53,     0,    54,    55,    56,    57,
    58,    59,    60,    61,    63,    62,     0,     0,    93,     0,
     0,     0,    64,    65,     0,     0,     0,    63,     0,     0,
     0,     0,     0,    66,     0,    64,    65,     0,     0,     0,
     0,     0,     0,     0,     0,    53,    66,    54,    55,    56,
    57,    58,    59,    60,    61,     0,    62,     0,    53,     0,
    54,    55,    56,    57,    58,    59,    60,    61,   108,    62,
     0,     0,     0,     0,     0,     0,    64,    65,     0,     0,
     0,   117,     0,     0,     0,     0,     0,    66,     0,    64,
    65,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    66
};

static const short yycheck[] = {    40,
    52,    46,    22,     3,    99,    46,    93,    98,     4,     0,
    58,    59,   148,   155,    62,    15,    64,    65,   243,     3,
    11,     3,    63,   133,     4,    16,    17,   137,    18,    37,
   157,    26,   154,    28,    23,    24,     3,   164,     4,    47,
    35,   163,    26,    33,    26,    45,    28,    26,    93,    28,
     4,   276,    93,    35,     4,   146,   151,   148,   194,    26,
   203,    35,   287,    43,    44,    31,    46,   108,    35,   212,
     3,    25,    63,     4,     9,    10,   117,    43,    44,     3,
    46,    31,   130,   131,   132,   227,    40,    41,    42,    43,
    44,    30,    46,    43,    44,     3,    46,   138,    27,    38,
   100,   122,   123,   194,   100,    30,   193,   250,    99,    40,
    41,    42,    43,    44,   155,    46,   112,    30,    26,   167,
    28,    18,    31,   233,    33,   268,   117,   128,   129,   272,
   273,    31,   275,    33,   277,    33,    30,   157,     3,     4,
    30,    30,   285,    19,    20,    21,    22,   147,   193,   190,
     3,    30,   193,   153,   154,    35,    36,    37,   154,    29,
   151,    26,    30,    28,   209,    15,   207,   163,   209,    31,
    35,    33,    16,    33,   226,    40,    41,    42,    43,    44,
    38,    46,     3,     4,    38,    27,   227,    58,    59,    60,
    61,    62,    38,    64,    65,    66,    26,     3,    28,   240,
   241,    26,   243,    28,    27,    26,     3,   248,    27,    11,
    12,    38,    27,    27,    35,    17,    33,    29,    26,    40,
    41,    42,    43,    44,    26,    46,    28,    26,    26,    18,
    32,    18,    26,   274,    39,   276,    31,    18,    29,   239,
   124,   125,   126,   127,    27,    27,   287,    18,    49,   120,
   121,   122,   123,   124,   125,   126,   127,   128,   129,   130,
   131,   132,     3,    39,     5,     6,     7,     8,     9,    10,
    11,    12,    27,    14,    27,    29,    27,    18,    26,    18,
    27,    27,    48,    27,    18,    26,    18,     0,     0,    30,
    11,   146,   239,    34,    35,    45,   167,    87,   143,   162,
   120,   112,    -1,   121,    45,     4,    47,   117,    49,    50,
    51,    52,    53,    54,    55,    56,    57,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    26,    14,    28,
    -1,    -1,    -1,    -1,    -1,    -1,    35,    -1,    -1,    -1,
    26,    40,    41,    42,    43,    44,    -1,    46,    34,    35,
    -1,    -1,    -1,    -1,    40,    41,    42,    43,    44,    45,
    46,     3,    -1,     5,     6,     7,     8,     9,    10,    11,
    12,    -1,    14,    -1,     3,    -1,     5,     6,     7,     8,
     9,    10,    11,    12,    26,    14,    -1,    -1,    30,    -1,
    -1,    -1,    34,    35,    -1,    -1,    -1,    26,    -1,    -1,
    -1,    -1,    -1,    45,    -1,    34,    35,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,     3,    45,     5,     6,     7,
     8,     9,    10,    11,    12,    -1,    14,    -1,     3,    -1,
     5,     6,     7,     8,     9,    10,    11,    12,    26,    14,
    -1,    -1,    -1,    -1,    -1,    -1,    34,    35,    -1,    -1,
    -1,    26,    -1,    -1,    -1,    -1,    -1,    45,    -1,    34,
    35,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    45
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 60 "kim.y"
{root=makeNode(N_PROGRAM,NIL,yyvsp[0],NIL); checkForwardReference();;
    break;}
case 2:
#line 63 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 3:
#line 64 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-1],yyvsp[0]);;
    break;}
case 4:
#line 67 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 5:
#line 68 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 6:
#line 71 "kim.y"
{yyval=setFunctionDeclaratorSpecifier(yyvsp[0],yyvsp[-1]);;
    break;}
case 7:
#line 72 "kim.y"
{yyval=setFunctionDeclaratorBody(yyvsp[-1],yyvsp[0]);;
    break;}
case 8:
#line 73 "kim.y"
{yyval=setFunctionDeclaratorSpecifier(yyvsp[0],makeSpecifier(int_type,0));;
    break;}
case 9:
#line 74 "kim.y"
{yyval=setFunctionDeclaratorBody(yyvsp[-1],yyvsp[0]);;
    break;}
case 10:
#line 77 "kim.y"
{yyval=NIL;;
    break;}
case 11:
#line 78 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 12:
#line 81 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 13:
#line 82 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-1],yyvsp[0]);;
    break;}
case 14:
#line 86 "kim.y"
{yyval=setDeclaratorListSpecifier(yyvsp[-1],yyvsp[-2]);;
    break;}
case 15:
#line 89 "kim.y"
{yyval=makeSpecifier(yyvsp[0],0);;
    break;}
case 16:
#line 90 "kim.y"
{yyval=makeSpecifier(0,yyvsp[0]);;
    break;}
case 17:
#line 91 "kim.y"
{yyval=updateSpecifier(yyvsp[0],yyvsp[-1],0);;
    break;}
case 18:
#line 92 "kim.y"
{yyval=updateSpecifier(yyvsp[0],0,yyvsp[-1]);;
    break;}
case 19:
#line 95 "kim.y"
{yyval=S_AUTO;;
    break;}
case 20:
#line 96 "kim.y"
{yyval=S_STATIC;;
    break;}
case 21:
#line 97 "kim.y"
{yyval=S_TYPEDEF;;
    break;}
case 22:
#line 100 "kim.y"
{yyval=makeDummyIdentifier();;
    break;}
case 23:
#line 101 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 24:
#line 104 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 25:
#line 105 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-2],yyvsp[0]);;
    break;}
case 26:
#line 108 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 27:
#line 109 "kim.y"
{yyval=setDeclaratorInit(yyvsp[-2],yyvsp[0]);;
    break;}
case 28:
#line 112 "kim.y"
{yyval=makeNode(N_INIT_LIST_ONE,NIL,yyvsp[0],NIL);;
    break;}
case 29:
#line 113 "kim.y"
{yyval=yyvsp[-1];;
    break;}
case 30:
#line 116 "kim.y"
{yyval=makeNode(N_INIT_LIST,yyvsp[0],NIL,makeNode(N_INIT_LIST_NIL,NIL,NIL,NIL));;
    break;}
case 31:
#line 117 "kim.y"
{yyval=makeNodeList(N_INIT_LIST,yyvsp[-2],yyvsp[0]);;
    break;}
case 32:
#line 120 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 33:
#line 121 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 34:
#line 122 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 35:
#line 125 "kim.y"
{yyval=setTypeStructOrEnumIdentifier(yyvsp[-1],yyvsp[0],ID_STRUCT);;
    break;}
case 36:
#line 126 "kim.y"
{yyval=current_id; current_level++;;
    break;}
case 37:
#line 127 "kim.y"
{checkForwardReference();yyval=setTypeField(yyvsp[-4],yyvsp[-1]);current_level--;current_id=yyvsp[-2];;
    break;}
case 38:
#line 128 "kim.y"
{yyval=makeType(yyvsp[0]);;
    break;}
case 39:
#line 128 "kim.y"
{yyval=current_id; current_level++;;
    break;}
case 40:
#line 129 "kim.y"
{checkForwardReference();yyval=setTypeField(yyvsp[-4],yyvsp[-1]);
		 current_level--;current_id=yyvsp[-2];;
    break;}
case 41:
#line 131 "kim.y"
{yyval=getTypeOfStructOrEnumRefIdentifier(yyvsp[-1],yyvsp[0],ID_STRUCT);;
    break;}
case 42:
#line 134 "kim.y"
{yyval=T_STRUCT;;
    break;}
case 43:
#line 135 "kim.y"
{yyval=T_UNION;;
    break;}
case 44:
#line 138 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 45:
#line 139 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-1],yyvsp[0]);;
    break;}
case 46:
#line 143 "kim.y"
{yyval=setStructDeclaratorListSpecifier(yyvsp[-1],yyvsp[-2]);;
    break;}
case 47:
#line 146 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 48:
#line 148 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-2],yyvsp[0]);;
    break;}
case 49:
#line 151 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 50:
#line 154 "kim.y"
{yyval=setTypeStructOrEnumIdentifier(T_ENUM,yyvsp[0],ID_ENUM);;
    break;}
case 51:
#line 155 "kim.y"
{yyval=setTypeField(yyvsp[-3],yyvsp[-1]);;
    break;}
case 52:
#line 156 "kim.y"
{yyval=makeType(T_ENUM);;
    break;}
case 53:
#line 157 "kim.y"
{yyval=setTypeField(yyvsp[-3],yyvsp[-1]);;
    break;}
case 54:
#line 158 "kim.y"
{yyval=getTypeOfStructOrEnumRefIdentifier(T_ENUM,yyvsp[0],ID_ENUM);;
    break;}
case 55:
#line 161 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 56:
#line 162 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-2],yyvsp[0]);;
    break;}
case 57:
#line 165 "kim.y"
{yyval=setDeclaratorKind(makeIdentifier(yyvsp[0]),ID_ENUM_LITERAL);;
    break;}
case 58:
#line 166 "kim.y"
{yyval=setDeclaratorKind(makeIdentifier(yyvsp[0]),ID_ENUM_LITERAL);;
    break;}
case 59:
#line 167 "kim.y"
{yyval=setDeclaratorInit(yyvsp[-2],yyvsp[0]);;
    break;}
case 60:
#line 170 "kim.y"
{yyval=setDeclaratorElementType(yyvsp[0],yyvsp[-1]);;
    break;}
case 61:
#line 171 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 62:
#line 174 "kim.y"
{yyval=makeType(T_POINTER);;
    break;}
case 63:
#line 175 "kim.y"
{yyval=setTypeElementType(yyvsp[0],makeType(T_POINTER));;
    break;}
case 64:
#line 178 "kim.y"
{yyval=makeIdentifier(yyvsp[0]);;
    break;}
case 65:
#line 179 "kim.y"
{yyval=yyvsp[-1];;
    break;}
case 66:
#line 180 "kim.y"
{yyval=setDeclaratorElementType(yyvsp[-3],setTypeExpr(makeType(T_ARRAY),yyvsp[-1]));;
    break;}
case 67:
#line 181 "kim.y"
{yyval=current_id;current_level++;;
    break;}
case 68:
#line 182 "kim.y"
{checkForwardReference(); current_id=yyvsp[-2]; current_level--;
														yyval=setDeclaratorElementType(yyvsp[-4],setTypeField(makeType(T_FUNC),yyvsp[-1]));;
    break;}
case 69:
#line 186 "kim.y"
{yyval=NIL;;
    break;}
case 70:
#line 187 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 71:
#line 190 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 72:
#line 191 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-2],setDeclaratorKind(makeDummyIdentifier(),ID_PARM));;
    break;}
case 73:
#line 194 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 74:
#line 195 "kim.y"
{yyval=linkDeclaratorList(yyvsp[-2],yyvsp[0]);;
    break;}
case 75:
#line 198 "kim.y"
{yyval=setParameterDeclaratorSpecifier(yyvsp[0],yyvsp[-1]);;
    break;}
case 76:
#line 200 "kim.y"
{yyval=setParameterDeclaratorSpecifier(setDeclaratorType(makeDummyIdentifier(),yyvsp[0]),yyvsp[-1]);;
    break;}
case 77:
#line 203 "kim.y"
{yyval=NIL;;
    break;}
case 78:
#line 204 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 79:
#line 207 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 80:
#line 208 "kim.y"
{yyval=makeType(T_POINTER);;
    break;}
case 81:
#line 209 "kim.y"
{yyval=setTypeElementType(yyvsp[0],makeType(T_POINTER));;
    break;}
case 82:
#line 212 "kim.y"
{yyval=yyvsp[-1];;
    break;}
case 83:
#line 213 "kim.y"
{yyval=setTypeExpr(makeType(T_ARRAY),yyvsp[-1]);;
    break;}
case 84:
#line 215 "kim.y"
{yyval=setTypeElementType(yyvsp[-3],setTypeExpr(makeType(T_ARRAY),yyvsp[-1]));;
    break;}
case 85:
#line 216 "kim.y"
{yyval=setTypeExpr(makeType(T_FUNC),yyvsp[-1]);;
    break;}
case 86:
#line 218 "kim.y"
{yyval=setTypeElementType(yyvsp[-3],setTypeExpr(makeType(T_FUNC),yyvsp[-1]));;
    break;}
case 87:
#line 221 "kim.y"
{yyval=makeNode(N_STMT_LIST_NIL,NIL,NIL,NIL);;
    break;}
case 88:
#line 222 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 89:
#line 225 "kim.y"
{yyval=makeNode(N_STMT_LIST,yyvsp[0],NIL,makeNode(N_STMT_LIST_NIL,NIL,NIL,NIL));;
    break;}
case 90:
#line 226 "kim.y"
{yyval=makeNodeList(N_STMT_LIST,yyvsp[-1],yyvsp[0]);;
    break;}
case 91:
#line 229 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 92:
#line 230 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 93:
#line 231 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 94:
#line 232 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 95:
#line 233 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 96:
#line 234 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 97:
#line 237 "kim.y"
{yyval=makeNode(N_STMT_LABEL_CASE,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 98:
#line 238 "kim.y"
{yyval=makeNode(N_STMT_LABEL_DEFAULT,NIL,yyvsp[0],NIL);;
    break;}
case 99:
#line 241 "kim.y"
{yyval=current_id;current_level++;;
    break;}
case 100:
#line 242 "kim.y"
{checkForwardReference();
		 yyval=makeNode(N_STMT_COMPOUND,yyvsp[-2],NIL,yyvsp[-1]); current_id=yyvsp[-3]; current_level--;;
    break;}
case 101:
#line 246 "kim.y"
{yyval=makeNode(N_STMT_EMPTY,NIL,NIL,NIL);;
    break;}
case 102:
#line 247 "kim.y"
{yyval=makeNode(N_STMT_EXPRESSION,NIL,yyvsp[-1],NIL);;
    break;}
case 103:
#line 250 "kim.y"
{yyval=makeNode(N_STMT_IF,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 104:
#line 252 "kim.y"
{yyval=makeNode(N_STMT_IF_ELSE,yyvsp[-4],yyvsp[-2],yyvsp[0]);;
    break;}
case 105:
#line 253 "kim.y"
{yyval=makeNode(N_STMT_SWITCH,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 106:
#line 256 "kim.y"
{yyval=makeNode(N_STMT_WHILE,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 107:
#line 258 "kim.y"
{yyval=makeNode(N_STMT_DO,yyvsp[-5],NIL,yyvsp[-2]);;
    break;}
case 108:
#line 259 "kim.y"
{yyval=makeNode(N_STMT_FOR,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 109:
#line 263 "kim.y"
{yyval=makeNode(N_FOR_EXP,yyvsp[-4],yyvsp[-2],yyvsp[0]);;
    break;}
case 110:
#line 266 "kim.y"
{yyval=NIL;;
    break;}
case 111:
#line 267 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 112:
#line 270 "kim.y"
{yyval=makeNode(N_STMT_RETURN,NIL,yyvsp[-1],NIL);;
    break;}
case 113:
#line 271 "kim.y"
{yyval=makeNode(N_STMT_CONTINUE,NIL,NIL,NIL);;
    break;}
case 114:
#line 272 "kim.y"
{yyval=makeNode(N_STMT_BREAK,NIL,NIL,NIL);;
    break;}
case 115:
#line 275 "kim.y"
{yyval=makeNode(N_ARG_LIST_NIL,NIL,NIL,NIL);;
    break;}
case 116:
#line 276 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 117:
#line 279 "kim.y"
{yyval=makeNode(N_ARG_LIST,yyvsp[0],NIL,makeNode(N_ARG_LIST_NIL,NIL,NIL,NIL));;
    break;}
case 118:
#line 281 "kim.y"
{yyval=makeNodeList(N_ARG_LIST,yyvsp[-2],yyvsp[0]);;
    break;}
case 119:
#line 284 "kim.y"
{yyval=NIL;;
    break;}
case 120:
#line 285 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 121:
#line 288 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 122:
#line 291 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 123:
#line 294 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 124:
#line 297 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 125:
#line 299 "kim.y"
{yyval=makeNode(N_EXP_ASSIGN,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 126:
#line 302 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 127:
#line 305 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 128:
#line 307 "kim.y"
{yyval=makeNode(N_EXP_OR,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 129:
#line 310 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 130:
#line 312 "kim.y"
{yyval=makeNode(N_EXP_AND,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 131:
#line 315 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 132:
#line 318 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 133:
#line 321 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 134:
#line 324 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 135:
#line 325 "kim.y"
{yyval=makeNode(N_EXP_EQL,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 136:
#line 326 "kim.y"
{yyval=makeNode(N_EXP_NEQ,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 137:
#line 329 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 138:
#line 330 "kim.y"
{yyval=makeNode(N_EXP_LSS,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 139:
#line 331 "kim.y"
{yyval=makeNode(N_EXP_GTR,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 140:
#line 332 "kim.y"
{yyval=makeNode(N_EXP_LEQ,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 141:
#line 333 "kim.y"
{yyval=makeNode(N_EXP_GEQ,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 142:
#line 336 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 143:
#line 339 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 144:
#line 340 "kim.y"
{yyval=makeNode(N_EXP_ADD,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 145:
#line 341 "kim.y"
{yyval=makeNode(N_EXP_SUB,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 146:
#line 344 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 147:
#line 345 "kim.y"
{yyval=makeNode(N_EXP_MUL,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 148:
#line 346 "kim.y"
{yyval=makeNode(N_EXP_DIV,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 149:
#line 347 "kim.y"
{yyval=makeNode(N_EXP_MOD,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 150:
#line 350 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 151:
#line 351 "kim.y"
{yyval=makeNode(N_EXP_CAST,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 152:
#line 354 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 153:
#line 355 "kim.y"
{yyval=makeNode(N_EXP_PRE_INC,NIL,yyvsp[0],NIL);;
    break;}
case 154:
#line 356 "kim.y"
{yyval=makeNode(N_EXP_PRE_DEC,NIL,yyvsp[0],NIL);;
    break;}
case 155:
#line 357 "kim.y"
{yyval=makeNode(N_EXP_AMP,NIL,yyvsp[0],NIL);;
    break;}
case 156:
#line 358 "kim.y"
{yyval=makeNode(N_EXP_STAR,NIL,yyvsp[0],NIL);;
    break;}
case 157:
#line 359 "kim.y"
{yyval=makeNode(N_EXP_NOT,NIL,yyvsp[0],NIL);;
    break;}
case 158:
#line 360 "kim.y"
{yyval=makeNode(N_EXP_MINUS,NIL,yyvsp[0],NIL);;
    break;}
case 159:
#line 361 "kim.y"
{yyval=makeNode(N_EXP_PLUS,NIL,yyvsp[0],NIL);;
    break;}
case 160:
#line 362 "kim.y"
{yyval=makeNode(N_EXP_SIZE_EXP,NIL,yyvsp[0],NIL);;
    break;}
case 161:
#line 363 "kim.y"
{yyval=makeNode(N_EXP_SIZE_TYPE,NIL,yyvsp[-1],NIL);;
    break;}
case 162:
#line 366 "kim.y"
{yyval=yyvsp[0];;
    break;}
case 163:
#line 367 "kim.y"
{yyval=makeNode(N_EXP_ARRAY,yyvsp[-3],NIL,yyvsp[-1]);;
    break;}
case 164:
#line 368 "kim.y"
{yyval=makeNode(N_EXP_FUNCTION_CALL,yyvsp[-3],NIL,yyvsp[-1]);;
    break;}
case 165:
#line 369 "kim.y"
{yyval=makeNode(N_EXP_STRUCT,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 166:
#line 370 "kim.y"
{yyval=makeNode(N_EXP_ARROW,yyvsp[-2],NIL,yyvsp[0]);;
    break;}
case 167:
#line 371 "kim.y"
{yyval=makeNode(N_EXP_POST_INC,NIL,yyvsp[-1],NIL);;
    break;}
case 168:
#line 372 "kim.y"
{yyval=makeNode(N_EXP_POST_DEC,NIL,yyvsp[-1],NIL);;
    break;}
case 169:
#line 375 "kim.y"
{yyval=makeNode(N_EXP_IDENT,NIL,getIdentifierDeclared(yyvsp[0]),NIL);;
    break;}
case 170:
#line 376 "kim.y"
{yyval=makeNode(N_EXP_INT_CONST,NIL,yyvsp[0],NIL);;
    break;}
case 171:
#line 377 "kim.y"
{yyval=makeNode(N_EXP_FLOAT_CONST,NIL,yyvsp[0],NIL);;
    break;}
case 172:
#line 378 "kim.y"
{yyval=makeNode(N_EXP_CHAR_CONST,NIL,yyvsp[0],NIL);;
    break;}
case 173:
#line 379 "kim.y"
{yyval=makeNode(N_EXP_STRING_LITERAL,NIL,yyvsp[0],NIL);;
    break;}
case 174:
#line 380 "kim.y"
{yyval=yyvsp[-1];;
    break;}
case 175:
#line 383 "kim.y"
{yyval=setTypeNameSpecifier(yyvsp[0],yyvsp[-1]);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 385 "kim.y"

extern char *yytext;
void yyerror(char *s)
{
		syntax_err++;
		printf("line  %d: %s near %s \n",line_no,s,yytext);
}
