gen:func.o gen.o lex.yy.o main.o print.o semantic.o y.tab.o
		gcc -o gen func.o gen.o lex.yy.o main.o print.o semantic.o y.tab.o
func.o:
		gcc -c func.c
gen.o:
		gcc -c gen.c
lex.yy.o:
		gcc -c lex.yy.c
main.o:
		gcc -c main.c
print.o:
		gcc -c print.c
semantic.o:
		gcc -c semantic.c
y.tab.o:
		gcc -c y.tab.c
